GET http://localhost:3003/api/blogs HTTP/1.1

###
//Adding blog
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json
# Authorization: 

{
    "author": "Shane Rodrigues",
    "title": "How to play Tennis",
    "url": "http://www.shanetennis.com",
    "likes": 1337
}

###
//deleting blog
DELETE http://localhost:3003/api/blogs/61f8d710d6860029d873bea4 HTTP/1.1
content-Type: application/json
Authorization: 


###
// Creating a user
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

# {
#     "blogs": [],
#     "username": "mluukai",
#     "name": "Matti Luukkainen",
#     "password": "pword"
# }

# {
#     "blogs": [],
#     "username": "root",
#     "name": "Super User",
#     "password": "sekret"
# }

{
    "blogs": [],
    "username": "sh2345",
    "name": "Shane Rodrigues",
    "password": "shane2010r"
}

###
//logging in as user
POST http://localhost:3003/api/login
content-Type: application/json

{
    "username": "duhmnb",
    "password": "passtheword"
}

###
//deleting user
DELETE http://localhost:3003/api/users/61f8cb69b309e94b1c372fe4 HTTP/1.1
content-Type: application/json
