GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{
    "author": "Jean Paul",
    "title": "Life of X",
    "url": "xqClOL.com",
    "likes": 199
}

###